version: '3.8'
services:
  weather-app:
    build:
      context: .
      target: development
    environment:
      - POSTGRESQL_PASSWORD=veritatis
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
